-- ============================================================
-- PENAMBAHAN GEJALA BARU (ID 24 - 60)
-- ============================================================
INSERT INTO gejala (id, nama_gujala) VALUES 
(24, 'Kulit berminyak'),
(25, 'Komedo hitam'),
(26, 'Komedo putih'),
(27, 'Kista di bawah kulit'),
(28, 'Bintik cokelat/hitam tidak simetris'),
(29, 'Tepi luka tidak beraturan'),
(30, 'Luka tidak sembuh-sembuh'),
(31, 'Warna berubah-ubah'),
(32, 'Sisik tebal keperakan'),
(33, 'Kulit retak/pecah-pecah'),
(34, 'Gatal di sela jari'),
(35, 'Kulit terbakar matahari'),
(36, 'Kemerahan berbentuk cincin'),
(37, 'Bercak putih di kulit'),
(38, 'Kehilangan pigmen'),
(39, 'Gatal di kulit kepala'),
(40, 'Ketombe'),
(41, 'Rambut rontok di area gatal'),
(42, 'Kulit kepala merah'),
(43, 'Jerawat di punggung'),
(44, 'Komedo di dada'),
(45, 'Beruntusan halus'),
(46, 'Gatal saat berkeringat'),
(47, 'Biang keringat'),
(48, 'Luka bakar ringan'),
(49, 'Kulit melepuh kecil-kecil'),
(50, 'Kutil kecil keras'),
(51, 'Kutil di telapak kaki'),
(52, 'Kutil di area kelamin'),
(53, 'Bercak merah saat terkena matahari'),
(54, 'Kulit sensitif berlebihan'),
(55, 'Kulit bernanah'),
(56, 'Bisul besar memerah'),
(57, 'Infeksi di bawah kuku'),
(58, 'Kuku rapuh/berubah warna'),
(59, 'Kulit menghitam tidak merata'),
(60, 'Flek hitam karena hormonal');
